### ISSUE TITLE
Email from account

### ISSUE THREAD

**Issue by coolacid** [PUNCH-Cyber/YaraGuardian#35]
By default all emails come from `webmaster@localhost` this doesn't work well for some mail gateways. 

Configuring `DEFAULT_FROM_EMAIL` in settings.py does change this from address, however should probably be configured from the upstream settings like all other settings.

**Comment by coolacid** [comment]
After further digging with Debug Off, I found https://github.com/PUNCH-Cyber/YaraGuardian/blob/master/core/models.py#L59 tries to build the email address from settings. This does not work when the login user is not the same as the domain user - IE: AWS SES.

**Comment by Taskr** [comment]
Hi @coolacid! Thanks for bringing this to our attention. Will update settings and email build logic to account for wider range of email configurations.

**Comment by Taskr** [comment]
DEFAULT_FROM_EMAIL is now able to be configured in upstream settings and is the email address used instead of the login user. This should help to account for situations such as AWS SES. 

In a situation where DEFAULT_FROM_EMAIL is not set, the default value will continue to be webmaster@localhost in DEBUG mode. For production mode, the default value will be the login user.

Please let us know if this adequately solves your issue.
